# Generated by Django 5.0.1 on 2024-11-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_personaldetails_file_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='file_attachment',
        ),
    ]
